name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      PORT: ${{ vars.PORT }}
      SECRET: ${{ secrets.SECRET }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: npm install

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./frontend

      - name: Check backend style
        run: npm run lint

      - name: Check frontend style
        run: npm run lint
        working-directory: ./frontend

      - name: Run backend tests
        run: npm test

      - name: Run frontend tests
        run: npm test
        working-directory: ./frontend

  tag_release:
    needs: [run_tests]
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  deployment:
    needs: [run_tests, tag_release]
    runs-on: ubumtu-20.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Deploy to Render
        if: ${{ github.event_name == 'push' }}
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
